sudo: true
language: node_js
node_js:
  - "8"
  - "node" 
install:
  - sudo rm /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo ln -s /usr/bin/cpp-4.9 /usr/bin/cpp
  - cc --version
  - npm install
  - npm run configure
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - cpp-4.9