sudo: false
language: node_js
node_js:
  - "6.5"
  - "7.0.0"
before_install:
  - pwd
  - git clone --depth=1 --branch=master https://github.com/drorgl/node-addon-tracer.git ../../drorgl/node-addon-tracer
  - pushd .
  - cd ../../drorgl/node-addon-tracer
  - npm install --ignore-scripts
  - popd
install:
  - npm install
script:
  - npm test
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9